name: limpiacasa
description: "Una app sencilla para hacer el quehacer de la casa poco a poco"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.3.1+24

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo.png
  adaptive_icon_background: "#0B1D33"
  adaptive_icon_foreground: assets/logo.png
  remove_alpha_ios: true

flutter:

  uses-material-design: true
  assets:
    - assets/logo.svg
    - assets/logo.png
